# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Russian ads
tagline:          'A DH exploration'
description:      'A digital humanities exploration of Russian influence on Facebook.'
url:              http://isawil.github.io
baseurl:          /russian-ads/

author:
  name:           'Isaac Williams'
  url:            https://twitter.com/isawil_

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/isawil/russian-ads
